### ISSUE TITLE
Hetio v0.2.3 breaks integration code

### ISSUE THREAD

**Issue by veleritas** [dhimmel/hetio#10] opened 2017-03-08 22:18 UTC
Hi Daniel,

Just wanted to note that the new assertions you added into v0.2.3 about whether a node or edge have already been integrated into the network breaks earlier code in the `integrate` repository.

Looking at the [blame](https://github.com/dhimmel/hetio/blame/master/hetio/hetnet.py) for `hetnet.py` shows that those assertion lines were added only 21 days ago with commit d32ba2a8e73267b5a63df9d6d7da61877f6c84f4, and are therefore very recent (I wasn't having these problems before).

For now I've just commented out the cells which add edges which already exist in the network, but I just wanted you to know that `dhimmel/integrate/integrate.ipynb` won't run directly anymore with the latest `hetio` release.

**Comment by dhimmel** [comment] 2017-03-08 22:19
Eek. Okay I'll look into this. Sorry!

**Comment by veleritas** [comment] 2017-03-08 23:52
The easy way might be to modify hetio so that if the node or edge already exists in the network, then the code just skips adding that node/edge again. This would probably be easier than modifying all of the integrate code to use `try/catch` statements to deal with all of the assertion errors.

**Comment by dhimmel** [comment] 2017-03-09 17:10
@veleritas as you suspected, d32ba2a8e73267b5a63df9d6d7da61877f6c84f4 adds a check for duplicate edge additions. However, duplicate nodes additions previously threw an error. I was surprised when I looked through the code and didn't saw that duplicate edges were allowed to be added. I definitely think attempting to add a duplicate edge should throw an error... allowing additions of duplicates edges will almost certainly lead to a host of other bugs and confusing behaviors down the road.

> The easy way might be to modify hetio so that if the node or edge already exists in the network, then the code just skips adding that node/edge again.

I'd rather implement these checks or error handing in `integrate.ipynb`. I'll look into where duplicate edges are being added in `integrate.ipynb` and attempt to resolve these issues. Hopefully, I can identify a solution that:

1. makes `integrate.ipynb` work with `hetio>=0.2.3`
2. reproduces Hetionet v1.0 exactly

I'm thinking that in the past when a duplicate edge was added, it would essentially overwrite the existing edge. So I'm crossing my fingers that [`drop_duplicates`](http://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.drop_duplicates.html) in pandas using `keep='last'` can save us here. Will let you know.

**Comment by dhimmel** [comment] 2017-03-09 22:03
Here's the situation we're dealing with.

The following issues exposed by https://github.com/dhimmel/hetio/commit/d32ba2a8e73267b5a63df9d6d7da61877f6c84f4 cause changes to the hetnet:

1. 2925 _Gene-interacts-Gene_ edges are self-loops. This makes sense (for example homodimers)
2. https://github.com/dhimmel/erc/issues/2: 2 ERC gene pairs were self-loops (this does not make sense, should be removed)

I believe, these changes will affect the hetnet compared to Hetionet v1.0. This is because previously the self-loops of bidirectional edges would be considered inverted and therefore not get saved.

The following issues exposed by https://github.com/dhimmel/hetio/commit/d32ba2a8e73267b5a63df9d6d7da61877f6c84f4 do not cause changes to the hetnet:

1. https://github.com/dhimmel/erc/issues/1: 1 ERC gene pair was duplicated. This does not make sense, Resolved by dropping the duplicate gene pair with `keep='last'`.
2. https://github.com/dhimmel/drugcentral/commit/0e085ddb6aa42be367c85eba424edea716bebd94: duplicated Compound-includes-PharmacologicClass edges. Resolved by removing duplicates upstream in `dhimmel/drugcentral`.

I currently believe these fixes will not affect the hetnet compared to Hetionet v1.0.

I'm still investigating the issue.

**Comment by dhimmel** [comment] 2017-03-09 22:35
# Effect on Project Rephetio

https://github.com/dhimmel/hetio/commit/d32ba2a8e73267b5a63df9d6d7da61877f6c84f4 enabled bidirectional self-loops in `hetio`. Here I'll assess the downstream effect on Project Rephetio of allowing self-loops in `integrate.ipynb`. 2925 new GiG and 2 new GcG edges would be added. When computing features, the path counts should stay the same as we exclude paths with duplicate nodes. However, degree-weighted path counts could change, since some nodes will now have a different degree.

Therefore I think it's best to filter self-loops in `integrate.ipynb` so we keep the old behavior. In future versions of Hetionet, we can remove the self-interaction filter.

@veleritas I implement a fix in https://github.com/dhimmel/integrate/pull/12. If you adopt these changes, you should be able to use `hetio v0.2.3`. I recommend the upgrade since the old `hetio` behaviors were essentially bugs. Let me know if this makes sense.

**Comment by dhimmel** [comment] 2018-04-04 19:05
I think there's nothing outstanding on this issue, so I'll close. Happy to reopen if it's still active.

**Closed by dhimmel** 2018-04-04 19:05 UTC
